### ISSUE TITLE
test project pretty unusable due to empty urls

### ISSUE THREAD

**Issue by bob-r** [grey0ne/django-protector#13]
https://github.com/grey0ne/django-protector/blob/master/test_project/application/urls.py#L4

Could https://github.com/SershLevi/PM be considered as a more advanced test project? BTW: it requires python 3.6 and django 2.

**Comment by grey0ne** [comment]
Test project primarily used to run test against project structure, not as a demo. Also, I still want it to stay python 2 compatible, so can't use SershLevi project. But I can reference it in the docs.
Also admin interface in test project fixed in recent commit.
